// Code generated by "viper-config"; DO NOT EDIT.

package config

import (
	"flag"
	"fmt"
	"os"



	"github.com/fsnotify/fsnotify"
	"github.com/spf13/pflag"
	"github.com/spf13/viper"
)

var C = Config{}
var watchFunc func()

func Init(watch func(), filePath ...string) {
	watchFunc = watch
	setFlags()
	setEnv()
	readConfigFile(filePath)
	setDefaults()
	readFromRemote()
	err := viper.Unmarshal(&C)
	if err != nil {
		panic(err)
	}
}

func setFlags() {

	pflag.String("etcd.url", "", "")
	pflag.CommandLine.AddGoFlagSet(flag.CommandLine)
	pflag.Parse()
	err := viper.BindPFlags(pflag.CommandLine)
	if err != nil {
		panic(err)
	}
}

func setEnv() {
	viper.AutomaticEnv()
	viper.SetEnvPrefix("app")

	_ = viper.BindEnv("etcd.url")
}

func setDefaults() {

	viper.SetDefault("etcd.url", "")
}

func readFromRemote() {
	
}

func readConfigFile(path []string) {
	env := os.Getenv("GO_ENV")
	if env != "" {
		viper.SetConfigName(env)
	} else {
		viper.SetConfigName("config")
	}
	if len(path) == 0 {
		viper.AddConfigPath(".")
	}else {
		for _, value := range path {
			viper.AddConfigPath(value)
		}
	}
	err := viper.ReadInConfig()
	if err != nil {
		fmt.Println(err)
		return
	}
	if watchFunc != nil {
		viper.WatchConfig()
		viper.OnConfigChange(func(e fsnotify.Event) {
			err := viper.Unmarshal(&C)
			if err != nil {
				fmt.Println(err)
				return
			}
			watchFunc()
		})
	}
}

