// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gate.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KickReq_KickReason int32

const (
	KickReq_LoginConnect KickReq_KickReason = 0
)

var KickReq_KickReason_name = map[int32]string{
	0: "LoginConnect",
}

var KickReq_KickReason_value = map[string]int32{
	"LoginConnect": 0,
}

func (x KickReq_KickReason) String() string {
	return proto.EnumName(KickReq_KickReason_name, int32(x))
}

func (KickReq_KickReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{0, 0}
}

type KickReq struct {
	Reason               KickReq_KickReason `protobuf:"varint,1,opt,name=reason,proto3,enum=pb.KickReq_KickReason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *KickReq) Reset()         { *m = KickReq{} }
func (m *KickReq) String() string { return proto.CompactTextString(m) }
func (*KickReq) ProtoMessage()    {}
func (*KickReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{0}
}

func (m *KickReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickReq.Unmarshal(m, b)
}
func (m *KickReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickReq.Marshal(b, m, deterministic)
}
func (m *KickReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickReq.Merge(m, src)
}
func (m *KickReq) XXX_Size() int {
	return xxx_messageInfo_KickReq.Size(m)
}
func (m *KickReq) XXX_DiscardUnknown() {
	xxx_messageInfo_KickReq.DiscardUnknown(m)
}

var xxx_messageInfo_KickReq proto.InternalMessageInfo

func (m *KickReq) GetReason() KickReq_KickReason {
	if m != nil {
		return m.Reason
	}
	return KickReq_LoginConnect
}

type KickRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickRes) Reset()         { *m = KickRes{} }
func (m *KickRes) String() string { return proto.CompactTextString(m) }
func (*KickRes) ProtoMessage()    {}
func (*KickRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{1}
}

func (m *KickRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickRes.Unmarshal(m, b)
}
func (m *KickRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickRes.Marshal(b, m, deterministic)
}
func (m *KickRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickRes.Merge(m, src)
}
func (m *KickRes) XXX_Size() int {
	return xxx_messageInfo_KickRes.Size(m)
}
func (m *KickRes) XXX_DiscardUnknown() {
	xxx_messageInfo_KickRes.DiscardUnknown(m)
}

var xxx_messageInfo_KickRes proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pb.KickReq_KickReason", KickReq_KickReason_name, KickReq_KickReason_value)
	proto.RegisterType((*KickReq)(nil), "pb.KickReq")
	proto.RegisterType((*KickRes)(nil), "pb.KickRes")
}

func init() { proto.RegisterFile("gate.proto", fileDescriptor_743bb58a714d8b7d) }

var fileDescriptor_743bb58a714d8b7d = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4f, 0x2c, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x8a, 0xe4, 0x62, 0xf7, 0xce,
	0x4c, 0xce, 0x0e, 0x4a, 0x2d, 0x14, 0xd2, 0xe3, 0x62, 0x2b, 0x4a, 0x4d, 0x2c, 0xce, 0xcf, 0x93,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0x12, 0xd3, 0x2b, 0x48, 0xd2, 0x83, 0x4a, 0x42, 0x69, 0x90,
	0x6c, 0x10, 0x54, 0x95, 0x92, 0x1c, 0x17, 0x17, 0x42, 0x54, 0x48, 0x80, 0x8b, 0xc7, 0x27, 0x3f,
	0x3d, 0x33, 0xcf, 0x39, 0x3f, 0x2f, 0x2f, 0x35, 0xb9, 0x44, 0x80, 0x41, 0x89, 0x13, 0x66, 0x74,
	0x71, 0x12, 0x1b, 0xd8, 0x42, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x69, 0x06, 0xd1, 0xcb,
	0x7e, 0x00, 0x00, 0x00,
}
