// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Platform int32

const (
	Platform_Self   Platform = 0
	Platform_Wechat Platform = 1
)

var Platform_name = map[int32]string{
	0: "Self",
	1: "Wechat",
}

var Platform_value = map[string]int32{
	"Self":   0,
	"Wechat": 1,
}

func (x Platform) String() string {
	return proto.EnumName(Platform_name, int32(x))
}

func (Platform) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

// 客户端信息
type ClientDesc struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientDesc) Reset()         { *m = ClientDesc{} }
func (m *ClientDesc) String() string { return proto.CompactTextString(m) }
func (*ClientDesc) ProtoMessage()    {}
func (*ClientDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *ClientDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientDesc.Unmarshal(m, b)
}
func (m *ClientDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientDesc.Marshal(b, m, deterministic)
}
func (m *ClientDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientDesc.Merge(m, src)
}
func (m *ClientDesc) XXX_Size() int {
	return xxx_messageInfo_ClientDesc.Size(m)
}
func (m *ClientDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientDesc.DiscardUnknown(m)
}

var xxx_messageInfo_ClientDesc proto.InternalMessageInfo

type LoginReq struct {
	Platform             Platform    `protobuf:"varint,1,opt,name=platform,proto3,enum=pb.Platform" json:"platform,omitempty"`
	PlatId               string      `protobuf:"bytes,2,opt,name=platId,proto3" json:"platId,omitempty"`
	PlatKey              string      `protobuf:"bytes,3,opt,name=platKey,proto3" json:"platKey,omitempty"`
	PlatDesc             *ClientDesc `protobuf:"bytes,4,opt,name=platDesc,proto3" json:"platDesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetPlatform() Platform {
	if m != nil {
		return m.Platform
	}
	return Platform_Self
}

func (m *LoginReq) GetPlatId() string {
	if m != nil {
		return m.PlatId
	}
	return ""
}

func (m *LoginReq) GetPlatKey() string {
	if m != nil {
		return m.PlatKey
	}
	return ""
}

func (m *LoginReq) GetPlatDesc() *ClientDesc {
	if m != nil {
		return m.PlatDesc
	}
	return nil
}

type LoginAckReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAckReq) Reset()         { *m = LoginAckReq{} }
func (m *LoginAckReq) String() string { return proto.CompactTextString(m) }
func (*LoginAckReq) ProtoMessage()    {}
func (*LoginAckReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *LoginAckReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAckReq.Unmarshal(m, b)
}
func (m *LoginAckReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAckReq.Marshal(b, m, deterministic)
}
func (m *LoginAckReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAckReq.Merge(m, src)
}
func (m *LoginAckReq) XXX_Size() int {
	return xxx_messageInfo_LoginAckReq.Size(m)
}
func (m *LoginAckReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAckReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAckReq proto.InternalMessageInfo

func (m *LoginAckReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginAckRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAckRes) Reset()         { *m = LoginAckRes{} }
func (m *LoginAckRes) String() string { return proto.CompactTextString(m) }
func (*LoginAckRes) ProtoMessage()    {}
func (*LoginAckRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *LoginAckRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAckRes.Unmarshal(m, b)
}
func (m *LoginAckRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAckRes.Marshal(b, m, deterministic)
}
func (m *LoginAckRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAckRes.Merge(m, src)
}
func (m *LoginAckRes) XXX_Size() int {
	return xxx_messageInfo_LoginAckRes.Size(m)
}
func (m *LoginAckRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAckRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAckRes proto.InternalMessageInfo

type LoginRes struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GateUrl              string   `protobuf:"bytes,2,opt,name=gateUrl,proto3" json:"gateUrl,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}

func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LoginRes) GetGateUrl() string {
	if m != nil {
		return m.GateUrl
	}
	return ""
}

func (m *LoginRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.Platform", Platform_name, Platform_value)
	proto.RegisterType((*ClientDesc)(nil), "pb.ClientDesc")
	proto.RegisterType((*LoginReq)(nil), "pb.LoginReq")
	proto.RegisterType((*LoginAckReq)(nil), "pb.LoginAckReq")
	proto.RegisterType((*LoginAckRes)(nil), "pb.LoginAckRes")
	proto.RegisterType((*LoginRes)(nil), "pb.LoginRes")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4f, 0x83, 0x40,
	0x10, 0x85, 0xdd, 0x52, 0x91, 0x0e, 0xb5, 0x21, 0x13, 0x63, 0xf6, 0x48, 0xd6, 0x0b, 0xe9, 0x81,
	0x43, 0xfd, 0x05, 0x46, 0x2f, 0xc6, 0x1e, 0xcc, 0x1a, 0xe3, 0x19, 0xe8, 0xb4, 0x92, 0xae, 0x2c,
	0xc2, 0x7a, 0xf0, 0x6f, 0xf8, 0x8b, 0xcd, 0x50, 0xa0, 0xdc, 0xde, 0xe3, 0xbd, 0x3c, 0xbe, 0x59,
	0x08, 0x8d, 0x3d, 0x94, 0x55, 0x5a, 0x37, 0xd6, 0x59, 0x9c, 0xd5, 0xb9, 0x5a, 0x02, 0x3c, 0x9a,
	0x92, 0x2a, 0xf7, 0x44, 0x6d, 0xa1, 0xfe, 0x04, 0x04, 0x5b, 0x6e, 0x68, 0xfa, 0xc6, 0x04, 0x82,
	0xda, 0x64, 0x6e, 0x6f, 0x9b, 0x2f, 0x29, 0x62, 0x91, 0xac, 0x36, 0xcb, 0xb4, 0xce, 0xd3, 0xd7,
	0xfe, 0x9b, 0x1e, 0x53, 0xbc, 0x05, 0x9f, 0xf5, 0xf3, 0x4e, 0xce, 0x62, 0x91, 0x2c, 0x74, 0xef,
	0x50, 0xc2, 0x15, 0xab, 0x17, 0xfa, 0x95, 0x5e, 0x17, 0x0c, 0x16, 0xd7, 0xa7, 0x6d, 0xfe, 0xa9,
	0x9c, 0xc7, 0x22, 0x09, 0x37, 0x2b, 0xde, 0x3e, 0xa3, 0xe8, 0x31, 0x57, 0x77, 0x10, 0x76, 0x4c,
	0x0f, 0xc5, 0x91, 0xb1, 0x6e, 0xe0, 0xd2, 0xd9, 0x23, 0x55, 0x1d, 0xd3, 0x42, 0x9f, 0x8c, 0xba,
	0x9e, 0x96, 0x5a, 0xb5, 0x1d, 0xef, 0x68, 0x31, 0x02, 0xef, 0xa7, 0xdc, 0xf5, 0x75, 0x96, 0xcc,
	0x75, 0xc8, 0x1c, 0xbd, 0x37, 0xa6, 0x07, 0x1e, 0xec, 0x79, 0xdc, 0x9b, 0x8c, 0xaf, 0x63, 0x08,
	0x86, 0xab, 0x31, 0x80, 0xf9, 0x1b, 0x99, 0x7d, 0x74, 0x81, 0x00, 0xfe, 0x07, 0x15, 0x9f, 0x99,
	0x8b, 0x44, 0xee, 0x77, 0x2f, 0x7a, 0xff, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x06, 0x03, 0x5f, 0x70,
	0x60, 0x01, 0x00, 0x00,
}
