// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameType int32

const (
	GameType_Unknown      GameType = 0
	GameType_Poker_Simple GameType = 1
	GameType_Poker_Ddz    GameType = 2
	GameType_Mahjong_Csmj GameType = 1000
)

var GameType_name = map[int32]string{
	0:    "Unknown",
	1:    "Poker_Simple",
	2:    "Poker_Ddz",
	1000: "Mahjong_Csmj",
}

var GameType_value = map[string]int32{
	"Unknown":      0,
	"Poker_Simple": 1,
	"Poker_Ddz":    2,
	"Mahjong_Csmj": 1000,
}

func (x GameType) String() string {
	return proto.EnumName(GameType_name, int32(x))
}

func (GameType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{0}
}

type Game_Poker_Ddz_Paixing int32

const (
	Game_Poker_Ddz_Unknown Game_Poker_Ddz_Paixing = 0
	Game_Poker_Ddz_Dan     Game_Poker_Ddz_Paixing = 1
	Game_Poker_Ddz_Dui     Game_Poker_Ddz_Paixing = 2
	Game_Poker_Ddz_Shun    Game_Poker_Ddz_Paixing = 3
	Game_Poker_Ddz_LianDui Game_Poker_Ddz_Paixing = 4
	Game_Poker_Ddz_Feiji   Game_Poker_Ddz_Paixing = 5
	Game_Poker_Ddz_LianFei Game_Poker_Ddz_Paixing = 6
	Game_Poker_Ddz_Zhadan  Game_Poker_Ddz_Paixing = 7
)

var Game_Poker_Ddz_Paixing_name = map[int32]string{
	0: "Unknown",
	1: "Dan",
	2: "Dui",
	3: "Shun",
	4: "LianDui",
	5: "Feiji",
	6: "LianFei",
	7: "Zhadan",
}

var Game_Poker_Ddz_Paixing_value = map[string]int32{
	"Unknown": 0,
	"Dan":     1,
	"Dui":     2,
	"Shun":    3,
	"LianDui": 4,
	"Feiji":   5,
	"LianFei": 6,
	"Zhadan":  7,
}

func (x Game_Poker_Ddz_Paixing) String() string {
	return proto.EnumName(Game_Poker_Ddz_Paixing_name, int32(x))
}

func (Game_Poker_Ddz_Paixing) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{5, 0}
}

// 1-10 gate server
// 10-30000 game server
//10-100 room msg
//100以上  game msg
// 30000-32767 other server
type C2SMsg_Type int32

const (
	C2SMsg_Unknown             C2SMsg_Type = 0
	C2SMsg_Ping                C2SMsg_Type = 1
	C2SMsg_Login               C2SMsg_Type = 2
	C2SMsg_CreateRoom          C2SMsg_Type = 3
	C2SMsg_EnterRoom           C2SMsg_Type = 10
	C2SMsg_StartGame           C2SMsg_Type = 11
	C2SMsg_LeaveRoom           C2SMsg_Type = 12
	C2SMsg_Poker_Ddz_Jiaofen   C2SMsg_Type = 100
	C2SMsg_Poker_Ddz_Chupai    C2SMsg_Type = 101
	C2SMsg_Poker_Ddz_Pass      C2SMsg_Type = 102
	C2SMsg_Poker_Simple_Chupai C2SMsg_Type = 120
)

var C2SMsg_Type_name = map[int32]string{
	0:   "Unknown",
	1:   "Ping",
	2:   "Login",
	3:   "CreateRoom",
	10:  "EnterRoom",
	11:  "StartGame",
	12:  "LeaveRoom",
	100: "Poker_Ddz_Jiaofen",
	101: "Poker_Ddz_Chupai",
	102: "Poker_Ddz_Pass",
	120: "Poker_Simple_Chupai",
}

var C2SMsg_Type_value = map[string]int32{
	"Unknown":             0,
	"Ping":                1,
	"Login":               2,
	"CreateRoom":          3,
	"EnterRoom":           10,
	"StartGame":           11,
	"LeaveRoom":           12,
	"Poker_Ddz_Jiaofen":   100,
	"Poker_Ddz_Chupai":    101,
	"Poker_Ddz_Pass":      102,
	"Poker_Simple_Chupai": 120,
}

func (x C2SMsg_Type) String() string {
	return proto.EnumName(C2SMsg_Type_name, int32(x))
}

func (C2SMsg_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{7, 0}
}

// 服务器发给客户端
type S2CMsg_Type int32

const (
	S2CMsg_Unknown S2CMsg_Type = 0
	S2CMsg_Confirm S2CMsg_Type = 1
	S2CMsg_Login   S2CMsg_Type = 2
)

var S2CMsg_Type_name = map[int32]string{
	0: "Unknown",
	1: "Confirm",
	2: "Login",
}

var S2CMsg_Type_value = map[string]int32{
	"Unknown": 0,
	"Confirm": 1,
	"Login":   2,
}

func (x S2CMsg_Type) String() string {
	return proto.EnumName(S2CMsg_Type_name, int32(x))
}

func (S2CMsg_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{8, 0}
}

type Poker struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Poker) Reset()         { *m = Poker{} }
func (m *Poker) String() string { return proto.CompactTextString(m) }
func (*Poker) ProtoMessage()    {}
func (*Poker) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{0}
}

func (m *Poker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Poker.Unmarshal(m, b)
}
func (m *Poker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Poker.Marshal(b, m, deterministic)
}
func (m *Poker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Poker.Merge(m, src)
}
func (m *Poker) XXX_Size() int {
	return xxx_messageInfo_Poker.Size(m)
}
func (m *Poker) XXX_DiscardUnknown() {
	xxx_messageInfo_Poker.DiscardUnknown(m)
}

var xxx_messageInfo_Poker proto.InternalMessageInfo

func (m *Poker) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Poker) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type Mahjong struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mahjong) Reset()         { *m = Mahjong{} }
func (m *Mahjong) String() string { return proto.CompactTextString(m) }
func (*Mahjong) ProtoMessage()    {}
func (*Mahjong) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{1}
}

func (m *Mahjong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mahjong.Unmarshal(m, b)
}
func (m *Mahjong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mahjong.Marshal(b, m, deterministic)
}
func (m *Mahjong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mahjong.Merge(m, src)
}
func (m *Mahjong) XXX_Size() int {
	return xxx_messageInfo_Mahjong.Size(m)
}
func (m *Mahjong) XXX_DiscardUnknown() {
	xxx_messageInfo_Mahjong.DiscardUnknown(m)
}

var xxx_messageInfo_Mahjong proto.InternalMessageInfo

func (m *Mahjong) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Mahjong) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type Zipai struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Zipai) Reset()         { *m = Zipai{} }
func (m *Zipai) String() string { return proto.CompactTextString(m) }
func (*Zipai) ProtoMessage()    {}
func (*Zipai) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{2}
}

func (m *Zipai) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zipai.Unmarshal(m, b)
}
func (m *Zipai) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zipai.Marshal(b, m, deterministic)
}
func (m *Zipai) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zipai.Merge(m, src)
}
func (m *Zipai) XXX_Size() int {
	return xxx_messageInfo_Zipai.Size(m)
}
func (m *Zipai) XXX_DiscardUnknown() {
	xxx_messageInfo_Zipai.DiscardUnknown(m)
}

var xxx_messageInfo_Zipai proto.InternalMessageInfo

func (m *Zipai) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Zipai) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 某个玩家id的手牌变化
type Data_Shoupai struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Pai                  []*Poker `protobuf:"bytes,2,rep,name=pai,proto3" json:"pai,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data_Shoupai) Reset()         { *m = Data_Shoupai{} }
func (m *Data_Shoupai) String() string { return proto.CompactTextString(m) }
func (*Data_Shoupai) ProtoMessage()    {}
func (*Data_Shoupai) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{4}
}

func (m *Data_Shoupai) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data_Shoupai.Unmarshal(m, b)
}
func (m *Data_Shoupai) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data_Shoupai.Marshal(b, m, deterministic)
}
func (m *Data_Shoupai) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data_Shoupai.Merge(m, src)
}
func (m *Data_Shoupai) XXX_Size() int {
	return xxx_messageInfo_Data_Shoupai.Size(m)
}
func (m *Data_Shoupai) XXX_DiscardUnknown() {
	xxx_messageInfo_Data_Shoupai.DiscardUnknown(m)
}

var xxx_messageInfo_Data_Shoupai proto.InternalMessageInfo

func (m *Data_Shoupai) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *Data_Shoupai) GetPai() []*Poker {
	if m != nil {
		return m.Pai
	}
	return nil
}

type Game_Poker_Ddz struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_Poker_Ddz) Reset()         { *m = Game_Poker_Ddz{} }
func (m *Game_Poker_Ddz) String() string { return proto.CompactTextString(m) }
func (*Game_Poker_Ddz) ProtoMessage()    {}
func (*Game_Poker_Ddz) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{5}
}

func (m *Game_Poker_Ddz) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_Poker_Ddz.Unmarshal(m, b)
}
func (m *Game_Poker_Ddz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_Poker_Ddz.Marshal(b, m, deterministic)
}
func (m *Game_Poker_Ddz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_Poker_Ddz.Merge(m, src)
}
func (m *Game_Poker_Ddz) XXX_Size() int {
	return xxx_messageInfo_Game_Poker_Ddz.Size(m)
}
func (m *Game_Poker_Ddz) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_Poker_Ddz.DiscardUnknown(m)
}

var xxx_messageInfo_Game_Poker_Ddz proto.InternalMessageInfo

// 斗地主_叫分
type Game_Poker_Ddz_Jiaofen struct {
	Fen                  int32    `protobuf:"varint,1,opt,name=fen,proto3" json:"fen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_Poker_Ddz_Jiaofen) Reset()         { *m = Game_Poker_Ddz_Jiaofen{} }
func (m *Game_Poker_Ddz_Jiaofen) String() string { return proto.CompactTextString(m) }
func (*Game_Poker_Ddz_Jiaofen) ProtoMessage()    {}
func (*Game_Poker_Ddz_Jiaofen) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{5, 0}
}

func (m *Game_Poker_Ddz_Jiaofen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_Poker_Ddz_Jiaofen.Unmarshal(m, b)
}
func (m *Game_Poker_Ddz_Jiaofen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_Poker_Ddz_Jiaofen.Marshal(b, m, deterministic)
}
func (m *Game_Poker_Ddz_Jiaofen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_Poker_Ddz_Jiaofen.Merge(m, src)
}
func (m *Game_Poker_Ddz_Jiaofen) XXX_Size() int {
	return xxx_messageInfo_Game_Poker_Ddz_Jiaofen.Size(m)
}
func (m *Game_Poker_Ddz_Jiaofen) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_Poker_Ddz_Jiaofen.DiscardUnknown(m)
}

var xxx_messageInfo_Game_Poker_Ddz_Jiaofen proto.InternalMessageInfo

func (m *Game_Poker_Ddz_Jiaofen) GetFen() int32 {
	if m != nil {
		return m.Fen
	}
	return 0
}

// 斗地主_出牌
type Game_Poker_Ddz_Chupai struct {
	Paixing              Game_Poker_Ddz_Paixing `protobuf:"varint,1,opt,name=paixing,proto3,enum=pb.Game_Poker_Ddz_Paixing" json:"paixing,omitempty"`
	Pai                  []*Poker               `protobuf:"bytes,2,rep,name=pai,proto3" json:"pai,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Game_Poker_Ddz_Chupai) Reset()         { *m = Game_Poker_Ddz_Chupai{} }
func (m *Game_Poker_Ddz_Chupai) String() string { return proto.CompactTextString(m) }
func (*Game_Poker_Ddz_Chupai) ProtoMessage()    {}
func (*Game_Poker_Ddz_Chupai) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{5, 1}
}

func (m *Game_Poker_Ddz_Chupai) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_Poker_Ddz_Chupai.Unmarshal(m, b)
}
func (m *Game_Poker_Ddz_Chupai) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_Poker_Ddz_Chupai.Marshal(b, m, deterministic)
}
func (m *Game_Poker_Ddz_Chupai) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_Poker_Ddz_Chupai.Merge(m, src)
}
func (m *Game_Poker_Ddz_Chupai) XXX_Size() int {
	return xxx_messageInfo_Game_Poker_Ddz_Chupai.Size(m)
}
func (m *Game_Poker_Ddz_Chupai) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_Poker_Ddz_Chupai.DiscardUnknown(m)
}

var xxx_messageInfo_Game_Poker_Ddz_Chupai proto.InternalMessageInfo

func (m *Game_Poker_Ddz_Chupai) GetPaixing() Game_Poker_Ddz_Paixing {
	if m != nil {
		return m.Paixing
	}
	return Game_Poker_Ddz_Unknown
}

func (m *Game_Poker_Ddz_Chupai) GetPai() []*Poker {
	if m != nil {
		return m.Pai
	}
	return nil
}

type Game_Poker_Ddz_Shoupai struct {
	Shoupai              []*Data_Shoupai `protobuf:"bytes,1,rep,name=shoupai,proto3" json:"shoupai,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Game_Poker_Ddz_Shoupai) Reset()         { *m = Game_Poker_Ddz_Shoupai{} }
func (m *Game_Poker_Ddz_Shoupai) String() string { return proto.CompactTextString(m) }
func (*Game_Poker_Ddz_Shoupai) ProtoMessage()    {}
func (*Game_Poker_Ddz_Shoupai) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{5, 2}
}

func (m *Game_Poker_Ddz_Shoupai) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_Poker_Ddz_Shoupai.Unmarshal(m, b)
}
func (m *Game_Poker_Ddz_Shoupai) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_Poker_Ddz_Shoupai.Marshal(b, m, deterministic)
}
func (m *Game_Poker_Ddz_Shoupai) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_Poker_Ddz_Shoupai.Merge(m, src)
}
func (m *Game_Poker_Ddz_Shoupai) XXX_Size() int {
	return xxx_messageInfo_Game_Poker_Ddz_Shoupai.Size(m)
}
func (m *Game_Poker_Ddz_Shoupai) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_Poker_Ddz_Shoupai.DiscardUnknown(m)
}

var xxx_messageInfo_Game_Poker_Ddz_Shoupai proto.InternalMessageInfo

func (m *Game_Poker_Ddz_Shoupai) GetShoupai() []*Data_Shoupai {
	if m != nil {
		return m.Shoupai
	}
	return nil
}

// 简单游戏，一次只出一张牌
type Game_Poker_Simple struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_Poker_Simple) Reset()         { *m = Game_Poker_Simple{} }
func (m *Game_Poker_Simple) String() string { return proto.CompactTextString(m) }
func (*Game_Poker_Simple) ProtoMessage()    {}
func (*Game_Poker_Simple) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{6}
}

func (m *Game_Poker_Simple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_Poker_Simple.Unmarshal(m, b)
}
func (m *Game_Poker_Simple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_Poker_Simple.Marshal(b, m, deterministic)
}
func (m *Game_Poker_Simple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_Poker_Simple.Merge(m, src)
}
func (m *Game_Poker_Simple) XXX_Size() int {
	return xxx_messageInfo_Game_Poker_Simple.Size(m)
}
func (m *Game_Poker_Simple) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_Poker_Simple.DiscardUnknown(m)
}

var xxx_messageInfo_Game_Poker_Simple proto.InternalMessageInfo

type Game_Poker_Simple_Chupai struct {
	Pai                  *Poker   `protobuf:"bytes,1,opt,name=pai,proto3" json:"pai,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_Poker_Simple_Chupai) Reset()         { *m = Game_Poker_Simple_Chupai{} }
func (m *Game_Poker_Simple_Chupai) String() string { return proto.CompactTextString(m) }
func (*Game_Poker_Simple_Chupai) ProtoMessage()    {}
func (*Game_Poker_Simple_Chupai) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{6, 0}
}

func (m *Game_Poker_Simple_Chupai) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_Poker_Simple_Chupai.Unmarshal(m, b)
}
func (m *Game_Poker_Simple_Chupai) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_Poker_Simple_Chupai.Marshal(b, m, deterministic)
}
func (m *Game_Poker_Simple_Chupai) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_Poker_Simple_Chupai.Merge(m, src)
}
func (m *Game_Poker_Simple_Chupai) XXX_Size() int {
	return xxx_messageInfo_Game_Poker_Simple_Chupai.Size(m)
}
func (m *Game_Poker_Simple_Chupai) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_Poker_Simple_Chupai.DiscardUnknown(m)
}

var xxx_messageInfo_Game_Poker_Simple_Chupai proto.InternalMessageInfo

func (m *Game_Poker_Simple_Chupai) GetPai() *Poker {
	if m != nil {
		return m.Pai
	}
	return nil
}

type C2SMsg struct {
	Cid                  int64       `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Head                 C2SMsg_Type `protobuf:"varint,2,opt,name=head,proto3,enum=pb.C2SMsg_Type" json:"head,omitempty"`
	Body                 *any.Any    `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	PlayerId             string      `protobuf:"bytes,4,opt,name=playerId,proto3" json:"playerId,omitempty"`
	RoomId               string      `protobuf:"bytes,5,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *C2SMsg) Reset()         { *m = C2SMsg{} }
func (m *C2SMsg) String() string { return proto.CompactTextString(m) }
func (*C2SMsg) ProtoMessage()    {}
func (*C2SMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{7}
}

func (m *C2SMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SMsg.Unmarshal(m, b)
}
func (m *C2SMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SMsg.Marshal(b, m, deterministic)
}
func (m *C2SMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SMsg.Merge(m, src)
}
func (m *C2SMsg) XXX_Size() int {
	return xxx_messageInfo_C2SMsg.Size(m)
}
func (m *C2SMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SMsg.DiscardUnknown(m)
}

var xxx_messageInfo_C2SMsg proto.InternalMessageInfo

func (m *C2SMsg) GetCid() int64 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *C2SMsg) GetHead() C2SMsg_Type {
	if m != nil {
		return m.Head
	}
	return C2SMsg_Unknown
}

func (m *C2SMsg) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *C2SMsg) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *C2SMsg) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type C2SMsg_EnterRoomReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SMsg_EnterRoomReq) Reset()         { *m = C2SMsg_EnterRoomReq{} }
func (m *C2SMsg_EnterRoomReq) String() string { return proto.CompactTextString(m) }
func (*C2SMsg_EnterRoomReq) ProtoMessage()    {}
func (*C2SMsg_EnterRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{7, 0}
}

func (m *C2SMsg_EnterRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SMsg_EnterRoomReq.Unmarshal(m, b)
}
func (m *C2SMsg_EnterRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SMsg_EnterRoomReq.Marshal(b, m, deterministic)
}
func (m *C2SMsg_EnterRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SMsg_EnterRoomReq.Merge(m, src)
}
func (m *C2SMsg_EnterRoomReq) XXX_Size() int {
	return xxx_messageInfo_C2SMsg_EnterRoomReq.Size(m)
}
func (m *C2SMsg_EnterRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SMsg_EnterRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_C2SMsg_EnterRoomReq proto.InternalMessageInfo

func (m *C2SMsg_EnterRoomReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type C2SMsg_LeaveRoomReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SMsg_LeaveRoomReq) Reset()         { *m = C2SMsg_LeaveRoomReq{} }
func (m *C2SMsg_LeaveRoomReq) String() string { return proto.CompactTextString(m) }
func (*C2SMsg_LeaveRoomReq) ProtoMessage()    {}
func (*C2SMsg_LeaveRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{7, 1}
}

func (m *C2SMsg_LeaveRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SMsg_LeaveRoomReq.Unmarshal(m, b)
}
func (m *C2SMsg_LeaveRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SMsg_LeaveRoomReq.Marshal(b, m, deterministic)
}
func (m *C2SMsg_LeaveRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SMsg_LeaveRoomReq.Merge(m, src)
}
func (m *C2SMsg_LeaveRoomReq) XXX_Size() int {
	return xxx_messageInfo_C2SMsg_LeaveRoomReq.Size(m)
}
func (m *C2SMsg_LeaveRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SMsg_LeaveRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_C2SMsg_LeaveRoomReq proto.InternalMessageInfo

func (m *C2SMsg_LeaveRoomReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// 服务端保证 客户端一个cid只回一个包, cid为0的包为服务器主动推送包，一个cid只有一个回包？
type S2CMsg struct {
	Cid                  int64       `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Head                 S2CMsg_Type `protobuf:"varint,2,opt,name=head,proto3,enum=pb.S2CMsg_Type" json:"head,omitempty"`
	Body                 *any.Any    `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Err                  *Error      `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
	PlayerId             string      `protobuf:"bytes,5,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *S2CMsg) Reset()         { *m = S2CMsg{} }
func (m *S2CMsg) String() string { return proto.CompactTextString(m) }
func (*S2CMsg) ProtoMessage()    {}
func (*S2CMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{8}
}

func (m *S2CMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CMsg.Unmarshal(m, b)
}
func (m *S2CMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CMsg.Marshal(b, m, deterministic)
}
func (m *S2CMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CMsg.Merge(m, src)
}
func (m *S2CMsg) XXX_Size() int {
	return xxx_messageInfo_S2CMsg.Size(m)
}
func (m *S2CMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CMsg.DiscardUnknown(m)
}

var xxx_messageInfo_S2CMsg proto.InternalMessageInfo

func (m *S2CMsg) GetCid() int64 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *S2CMsg) GetHead() S2CMsg_Type {
	if m != nil {
		return m.Head
	}
	return S2CMsg_Unknown
}

func (m *S2CMsg) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *S2CMsg) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *S2CMsg) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.GameType", GameType_name, GameType_value)
	proto.RegisterEnum("pb.Game_Poker_Ddz_Paixing", Game_Poker_Ddz_Paixing_name, Game_Poker_Ddz_Paixing_value)
	proto.RegisterEnum("pb.C2SMsg_Type", C2SMsg_Type_name, C2SMsg_Type_value)
	proto.RegisterEnum("pb.S2CMsg_Type", S2CMsg_Type_name, S2CMsg_Type_value)
	proto.RegisterType((*Poker)(nil), "pb.Poker")
	proto.RegisterType((*Mahjong)(nil), "pb.Mahjong")
	proto.RegisterType((*Zipai)(nil), "pb.Zipai")
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*Data_Shoupai)(nil), "pb.Data_Shoupai")
	proto.RegisterType((*Game_Poker_Ddz)(nil), "pb.Game_Poker_Ddz")
	proto.RegisterType((*Game_Poker_Ddz_Jiaofen)(nil), "pb.Game_Poker_Ddz.Jiaofen")
	proto.RegisterType((*Game_Poker_Ddz_Chupai)(nil), "pb.Game_Poker_Ddz.Chupai")
	proto.RegisterType((*Game_Poker_Ddz_Shoupai)(nil), "pb.Game_Poker_Ddz.Shoupai")
	proto.RegisterType((*Game_Poker_Simple)(nil), "pb.Game_Poker_Simple")
	proto.RegisterType((*Game_Poker_Simple_Chupai)(nil), "pb.Game_Poker_Simple.Chupai")
	proto.RegisterType((*C2SMsg)(nil), "pb.C2SMsg")
	proto.RegisterType((*C2SMsg_EnterRoomReq)(nil), "pb.C2SMsg.EnterRoomReq")
	proto.RegisterType((*C2SMsg_LeaveRoomReq)(nil), "pb.C2SMsg.LeaveRoomReq")
	proto.RegisterType((*S2CMsg)(nil), "pb.S2CMsg")
}

func init() { proto.RegisterFile("main.proto", fileDescriptor_7ed94b0a22d11796) }

var fileDescriptor_7ed94b0a22d11796 = []byte{
	// 795 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5b, 0x6e, 0xdb, 0x46,
	0x14, 0x15, 0x5f, 0xa2, 0x74, 0xa5, 0x28, 0xe3, 0x69, 0x9a, 0xaa, 0x14, 0x50, 0x18, 0x2c, 0x52,
	0x08, 0x31, 0x4a, 0x03, 0x6c, 0xf3, 0xd3, 0x3f, 0x43, 0x76, 0x8c, 0x34, 0x0e, 0x20, 0x50, 0xed,
	0x4f, 0x02, 0x54, 0x18, 0x89, 0x23, 0x6a, 0x2c, 0x71, 0x86, 0x21, 0x29, 0xd7, 0xea, 0x66, 0xfa,
	0xd7, 0x6d, 0x74, 0x09, 0xdd, 0x46, 0x97, 0x51, 0xcc, 0xf0, 0x61, 0xca, 0x6e, 0x0b, 0x23, 0x7f,
	0xf7, 0x71, 0xe6, 0x3e, 0xce, 0x3d, 0x24, 0x40, 0x4c, 0x18, 0xf7, 0x92, 0x54, 0xe4, 0x02, 0xeb,
	0xc9, 0xc2, 0x19, 0x45, 0x42, 0x44, 0x5b, 0x7a, 0xaa, 0x22, 0x8b, 0xdd, 0xea, 0x94, 0xc6, 0x49,
	0xbe, 0x2f, 0x00, 0xce, 0x97, 0xf7, 0x93, 0x84, 0x57, 0x29, 0x88, 0x48, 0x4e, 0x4b, 0xbb, 0xb7,
	0x15, 0x51, 0x55, 0xd4, 0x3d, 0x01, 0x6b, 0x2a, 0x36, 0x34, 0xc5, 0x03, 0xd0, 0x59, 0x38, 0xd4,
	0x8e, 0xb5, 0xf1, 0x93, 0x40, 0x67, 0x21, 0xc6, 0x60, 0x86, 0x34, 0x5b, 0x0e, 0xf5, 0x63, 0x6d,
	0xdc, 0x0d, 0x94, 0xed, 0x7e, 0x0b, 0xf6, 0x3b, 0xb2, 0xbe, 0x16, 0x3c, 0x7a, 0x14, 0xfc, 0x04,
	0xac, 0xf7, 0x2c, 0x21, 0xec, 0x51, 0xe0, 0x57, 0x60, 0x5d, 0xa4, 0xa9, 0x48, 0x65, 0x72, 0x29,
	0x42, 0xaa, 0xe0, 0x56, 0xa0, 0x6c, 0x3c, 0x04, 0x3b, 0xa6, 0x59, 0x46, 0x22, 0x5a, 0xbe, 0xa9,
	0x5c, 0xf7, 0x12, 0xfa, 0xe7, 0x24, 0x27, 0xf3, 0xd9, 0x5a, 0xec, 0x64, 0x2b, 0x07, 0x3a, 0xc9,
	0x96, 0xec, 0x69, 0xfa, 0xa6, 0x68, 0xd8, 0x0d, 0x6a, 0x1f, 0x8f, 0xc0, 0x48, 0x08, 0x1b, 0xea,
	0xc7, 0xc6, 0xb8, 0xe7, 0x77, 0xbd, 0x64, 0xe1, 0xa9, 0xd5, 0x03, 0x19, 0x75, 0xff, 0xd0, 0x61,
	0x70, 0x49, 0x62, 0x3a, 0x57, 0xb1, 0xf9, 0x79, 0xf8, 0x9b, 0x33, 0x02, 0xfb, 0x47, 0x46, 0xc4,
	0x8a, 0x72, 0x8c, 0xc0, 0x58, 0x51, 0x5e, 0xce, 0x24, 0x4d, 0xe7, 0x03, 0xb4, 0x27, 0x6b, 0xd5,
	0xf2, 0x7b, 0xb0, 0x13, 0xc2, 0x6e, 0x19, 0x8f, 0x54, 0x7e, 0xe0, 0x3b, 0xb2, 0xf4, 0x61, 0x2d,
	0x6f, 0x5a, 0x20, 0x82, 0x0a, 0xfa, 0xbf, 0xc3, 0x38, 0xaf, 0xc0, 0xae, 0x16, 0x7a, 0x09, 0x76,
	0x56, 0x98, 0x43, 0x4d, 0x61, 0x91, 0xc4, 0x36, 0x77, 0x0e, 0x2a, 0x80, 0xbb, 0x04, 0xbb, 0xec,
	0x83, 0x7b, 0x60, 0xff, 0xcc, 0x37, 0x5c, 0xfc, 0xca, 0x51, 0x0b, 0xdb, 0x60, 0x9c, 0x13, 0x8e,
	0x34, 0x65, 0xec, 0x18, 0xd2, 0x71, 0x07, 0xcc, 0xd9, 0x7a, 0xc7, 0x91, 0x21, 0x81, 0x57, 0x8c,
	0x70, 0x19, 0x36, 0x71, 0x17, 0xac, 0xd7, 0x94, 0x5d, 0x33, 0x64, 0x55, 0xf1, 0xd7, 0x94, 0xa1,
	0x36, 0x06, 0x68, 0xbf, 0x5f, 0x93, 0x90, 0x70, 0x64, 0xbb, 0x3f, 0xc0, 0x51, 0x63, 0xb7, 0x19,
	0x8b, 0x93, 0x2d, 0x75, 0x5e, 0xd4, 0x6c, 0x94, 0x7b, 0x49, 0x26, 0x1e, 0x92, 0xfc, 0xbb, 0x01,
	0xed, 0x89, 0x3f, 0x7b, 0x97, 0x45, 0x92, 0xd1, 0x65, 0x29, 0x0a, 0x23, 0x90, 0x26, 0xfe, 0x1a,
	0xcc, 0x35, 0x25, 0xa1, 0xba, 0xf0, 0xc0, 0x7f, 0x2a, 0x9f, 0x16, 0x58, 0xef, 0xa7, 0x7d, 0x42,
	0x03, 0x95, 0xc4, 0x63, 0x30, 0x17, 0x22, 0xdc, 0x0f, 0x0d, 0x55, 0xff, 0x99, 0x57, 0x48, 0xde,
	0xab, 0x24, 0xef, 0x9d, 0xf1, 0x7d, 0xa0, 0x10, 0x07, 0x4a, 0x30, 0xef, 0x29, 0xe1, 0x39, 0xb4,
	0x53, 0x21, 0xe2, 0x37, 0xe1, 0xd0, 0x52, 0x99, 0xd2, 0x73, 0xbe, 0x82, 0xfe, 0x05, 0xcf, 0x69,
	0x1a, 0x08, 0x11, 0x07, 0xf4, 0x63, 0x43, 0xb8, 0x5d, 0x29, 0x5c, 0x99, 0xbf, 0xa2, 0xe4, 0x86,
	0xfe, 0x47, 0xde, 0xfd, 0x53, 0x03, 0x53, 0x0e, 0x7b, 0x48, 0x7f, 0x07, 0xcc, 0x29, 0xe3, 0x11,
	0xd2, 0x24, 0xbf, 0x57, 0xf2, 0xe3, 0x43, 0x3a, 0x1e, 0x00, 0x4c, 0x52, 0x4a, 0x72, 0x55, 0x0b,
	0x19, 0xf8, 0x09, 0x74, 0xeb, 0xd6, 0x08, 0xa4, 0x3b, 0xcb, 0x49, 0x9a, 0x4b, 0xaa, 0x51, 0x4f,
	0xba, 0x75, 0x63, 0xd4, 0xc7, 0x9f, 0xc3, 0x51, 0x2d, 0xad, 0x79, 0xa9, 0x51, 0x14, 0xe2, 0x67,
	0x80, 0xee, 0xc2, 0xc5, 0x3d, 0x10, 0xc5, 0x18, 0x06, 0x77, 0xd1, 0x29, 0xc9, 0x32, 0xb4, 0xc2,
	0x5f, 0xc0, 0x67, 0xcd, 0xfb, 0x55, 0xe0, 0x5b, 0xf7, 0x2f, 0x0d, 0xda, 0x33, 0x7f, 0xf2, 0xe8,
	0x0b, 0x15, 0xd8, 0x4f, 0xbb, 0xd0, 0x08, 0x0c, 0x9a, 0xa6, 0xea, 0x38, 0xa5, 0x54, 0xd4, 0x1f,
	0x20, 0x90, 0xd1, 0x83, 0xf3, 0x59, 0x87, 0xe7, 0x73, 0x4f, 0xfe, 0x8d, 0xe5, 0x1e, 0xd8, 0x13,
	0xc1, 0x57, 0x2c, 0x8d, 0x0f, 0x88, 0x7e, 0xf9, 0x16, 0x3a, 0x92, 0xc4, 0x87, 0x0f, 0x10, 0xf4,
	0x9b, 0x1c, 0x20, 0x4d, 0xb2, 0x5c, 0x33, 0x85, 0x74, 0x7c, 0x04, 0xfd, 0xf2, 0x77, 0x37, 0x9f,
	0x64, 0xf1, 0x35, 0xfa, 0xdb, 0xf6, 0x3f, 0x80, 0x79, 0x49, 0x72, 0x8a, 0x5d, 0x30, 0xdf, 0xb2,
	0xe5, 0x06, 0xf7, 0xe4, 0xd4, 0xd2, 0x0a, 0xe8, 0x47, 0xa7, 0xe1, 0x64, 0x6e, 0x0b, 0x9f, 0x82,
	0x3d, 0xa3, 0x3c, 0x94, 0x54, 0xc2, 0x1d, 0x55, 0xce, 0xf3, 0x07, 0x8c, 0x5c, 0xc8, 0x7f, 0xb8,
	0xdb, 0xf2, 0x7f, 0x29, 0x87, 0xc6, 0x2f, 0x2a, 0xa3, 0x2f, 0xdf, 0x29, 0x53, 0xd6, 0x6f, 0x7a,
	0xb2, 0x81, 0x07, 0x1d, 0xe5, 0x9d, 0x2d, 0x37, 0xf8, 0x69, 0x9d, 0x3b, 0x2b, 0x86, 0xb9, 0x17,
	0xc8, 0xdc, 0x96, 0xef, 0xc9, 0xe1, 0x63, 0x8a, 0xbf, 0x01, 0x08, 0xe8, 0x92, 0xb2, 0x1b, 0x5a,
	0xcf, 0x56, 0x7c, 0x68, 0x4e, 0x63, 0x4e, 0xb7, 0xb5, 0x68, 0xab, 0x09, 0xbf, 0xfb, 0x27, 0x00,
	0x00, 0xff, 0xff, 0xb6, 0x73, 0xc8, 0xc3, 0x85, 0x06, 0x00, 0x00,
}
